food_menu/food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    path('',views.IndexClassView.as_view(),name="index"),
    path('<int:pk>/',views.FoodDetail.as_view(),name="detail"),
    path('item/',views.item,name="item"),
    #add items
    path('add/',views.CreateItem.as_view(),name='create_item'),
    #edit items
    path('update/<int:id>/',views.update_item,name="update_item"),
    #delete items
    path('delete/<int:id>',views.delete_item,name='delete_item')
]

food_menu/food_menu/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("food/",include('food.urls')),
    path('register/',user_views.register,name="register"),
    path('login',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name="profile")
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food_menu/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Item(models.Model):
    
    def __str__(self):
        return self.item_name
    
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField( max_length=500,default="https://static.wixstatic.com/media/bf242e_6133b4ae6a104cc2b50d70179f35efea~mv2.jpg/v1/fill/w_500,h_376,al_c,lg_1,q_80,enc_auto/food-placeholder.jpg")
    
    
    def get_absolute_url(self):
        return reverse("food:detail",kwargs={"pk":self.pk})

food_menu/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    locations = models.CharField(max_length=100)
    
    def __str__(self) :
        return self.user.username

food_menu/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']
    

food_menu/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food_menu/food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# Create your views here.
def index(request):
    item_list = Item.objects.all()
    
    context={
        'item_list':item_list,
        
    }
    return render(request,'food/index.html',context)

class IndexClassView(ListView):
    model = Item;
    template_name = 'food/index.html'
    context_object_name = 'item_list'


def item(request):
    return HttpResponse('This is the Item Page')

def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item':item,
    }
    return render(request,'food/detail.html',context)

class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'

def create_item(request):
    
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{'form':form})

class CreateItem(CreateView):
    model = Item
    template_name = 'food/item-form.html'
    fields = ['item_name','item_desc','item_price','item_image']
    
    def form_valid(self,form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)
def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)
    
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{ 'form':form, 'item':item })
def delete_item(request,id):
    item = Item.objects.get(id=id)
    
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    return render(request,'food/item-delete.html',{ 'item':item })

food_menu/users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required
# Create your views here.
 
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome { username }, You are Logged in.....')
            return redirect('login')
    else:
        form =RegisterForm()
    return render (request,'users/register.html',{ 'form':form })     
@login_required
def profilepage(request):
    return render(request,'users/profile.html')

food_menu/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Vinsmoke Sanji</title>

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />

    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>

    <link rel="stylesheet" href="{% static 'food/style.css' %}" />
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a href="#" class="navbar-brand brand">Vinsmoke Sanji</a>

      <div class="navbar">
        <a class="nav-item nav-link" href="{% url 'food:create_item' %}"
          >Add Item</a
        >
        <a class="nav-item nav-link" href="#">Delete Item</a>
        <a class="nav-item nav-link" href="#">View Item</a>
        {% if user.is_authenticated %}
        <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
        <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
        {% else %}
        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
        {% endif %}
      </div>
    </nav>
    {% if messages %} {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %} {% endif %} {% block body %} {% endblock %}
  </body>
</html>

food_menu/food/templates/food/detail.html
{% extends "food/base.html" %} {% block body %}

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <img width="300px" src="{{ item.item_image }}" class="card" />
    </div>
    <div class = "col-md-6">
      <h1>{{ object.item_name }}</h1>
      <h2>{{ object.item_desc }}</h2>
      <h3>{{ object.item_price }}</h3>
      <a href="{% url 'food:delete_item' item.id %}" class="btn btn-outline-danger">Delete</a>
    </div>
  </div>
</div>
{% endblock %}

food_menu/food/templates/food/index.html
{% extends "food/base.html" %}
<!DOCTYPE html>
<html>
    <head>
        <title>Vinsmoke Sanji</title>
    </head>
    <body>

       {% block body%}
        {% for item in item_list %}
        <div class="row">
            <div class="col-md-2 offset-md-2 custom-padding">
                <img class="card " width="150px" src="{{ item.item_image }}">
            </div>
            <div class="col-md-4 custom-padding">
                <h3>{{ item.item_name }}</h3>
                <h5>{{ item.item_desc }}</h5>
                <h6>${{ item.item_price }}</h6>
                <h4>Posted by:- {{ item.user_name }}</h4>

            </div>
            <div class="col-md-2 custom-padding">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-outline-success">Details</a>
            </div>
            <div class="col-md-2 padding">
                <a href="{% url 'food:update_item' item.id %}" class="btn btn-outline-secondary">Edit Item</a>
            </div>
        </div>
        {% endfor %}
       {% endblock%}

    </body>
</html>

food_menu/food/templates/food/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }}</h2>
    <button type="submit">Confirm</button
</form>

food_menu/food/templates/food/item-form.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Add Item
                    </div>
                </div>
                <div class="class-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label for="{{ field.id_for_label }}" class="custom-label-style">{{ field.label }}</label>
                                {{ field }}
                                {{ field.errors }}
                            </div>
                        {% endfor %}
                        <button class="btn btn-outline-success" type="submit">Add</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

food_menu/users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                <div class="class-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button class="btn btn-outline-success" type=submit>Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
 

{% endblock %}


food_menu/users/templates/users/logout.html
<h1>you have been logged out</h1>

food_menu/users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img width="100px" height="100px"  src="{{ user.profile.image.url }}">

food_menu/users/templates/users/register.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Register
                    </div>
                </div>
                <div class="class-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                <br>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button class="btn btn-outline-success" type="submit">Signup</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
 

{% endblock %}



